### PR TITLE
Fix: Current tier/trial banner with multiple orgs

### PR DESCRIPTION
**Pull request by WcaleNieWolny**
## Summary

This PR solves the issue https://github.com/Cap-go/capgo/issues/526. It does so by making the following changes:

The banner will NEVER appear on this screen:
image

A banner will appear for the appropriate trial/tier on the app page. What I mean by that is that if user A own app `com.demo.app` and invites user B that owns `com.apple.stock` and user A has a valid plan but user B does not when user B clicks on `com.demo.app` he will see the banner that user A would see.

For the owner it will look something like this:
image

But for the invited user it will look like this:

image

As you can see, there is a difference. This is because the user B (the invited one) CANNOT upgrade the tier of the organization owner. If you click on the information icon you will be informed about it.

image

If, however you still try to upgrade the capgo tier you will be warned that it's only going to affect the apps you own

image

This warning does not appear if you are not invited to any organizations

image

## Screenshots

See above

## Checklist

- [x] My code follows the code style of this project and passes `bun run lint-backend && bun run lint`.
- [x] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://github.com/Cap-go/website) accordingly. (TODO)
- [ ] My change has adequate E2E test coverage.
- [x] I have tested my code manually, and I have provided steps how to reproduce my tests 

/claim #526

### CODE REVIEW

**Comment by WcaleNieWolny** [comment]
**DO NOT MERGE UNTIL THE DOCUMENTATION CHANGES ARE COMPLETE**

**Comment by WcaleNieWolny** [comment]
Documentation pr: https://github.com/Cap-go/website/pull/178

image


Ready to review @riderx

**Comment by riderx** [comment]
I don’t understand on the home we see only the apps of the org, so why do hide the modal at that time ?

**Comment by WcaleNieWolny** [comment]
> I don’t understand on the home we see only the apps of the org

No we do not - the org switcher does not do ANYTHING unless you are in settings

**Comment by riderx** [comment]
Wait what ?!?
That a huge issue

**Pull request merged**
