### PR TITLE
fix: weird scrollbar in the UI

### PR DESCRIPTION
**Pull request by kremedev**
fix: #320 
/claim #320

### CODE REVIEW

**Comment by WcaleNieWolny** [comment]
As you can see here:

https://github.com/Cap-go/capgo/assets/50914789/e61e3a31-7190-466f-ba82-c583ed14ef95

There now exists 2 scrollbars. In chromium based browsers only 1 is active and in Firefox both are active

**Comment by WcaleNieWolny** [comment]
This works

https://github.com/Cap-go/capgo/assets/50914789/bcb4e506-c4d1-4aeb-bb1d-ddbe7c4fd6c5

**Review by WcaleNieWolny — APPROVED** [review]

**Review by WcaleNieWolny — COMMENTED** [review]
I do not see exactly what was changed by the latest PR, but after further testing I found something wierd

(Left = firefox, right = chrome)
image

image

Can you see if you can fix this inactive scroll bar?

**Comment by kremedev** [comment]
Removed all inactive scrollbars except the language dropdown and sidebars.

**Review by WcaleNieWolny — APPROVED** [review]
Tested latest changes locally, looks good 💪

**Pull request merged**
