### PR TITLE
fix(docs): improve instructions for local development

### PR DESCRIPTION
**Pull request by ayewo**
Fix for https://github.com/Cap-go/capacitor-updater/issues/238 so I can /claim Cap-go/capacitor-updater#238

### CODE REVIEW

**Comment by riderx** [comment]
Can you delete the commented lines ?

**Comment by ayewo** [comment]
Done.

By removing the commented out SQL statements, these 4 files became empty so I deleted them. I hope this is fine?

```bash
deleted:    supabase/migrations/20230619105940_orgs.sql
deleted:    supabase/migrations/20230726140052_on_user_delete.sql
deleted:    supabase/migrations/20230804040106_add_stripe.sql
deleted:    supabase/migrations/20230804043519_add_big_query.sql
```

**Comment by riderx** [comment]
I'm not sure to understand, do you have the org table in your seed now ?

**Comment by riderx** [comment]
i think you maybe remove a bit too much things ^^
I thought you removed only what was bugging supabase but there also usefull tables in that ^^

**Comment by ayewo** [comment]
The changes I made were so I could to get `supabase start` to work without errors so I could run the app locally.

**Comment by ayewo** [comment]
If you want me to add the `org` table and others back along with seed data, it's going to be more than what you are offering.

**Comment by ayewo** [comment]
@riderx what do you suggest?

**Comment by riderx** [comment]
i'm not sure to understand, it was already in the migration file, it should works, why did you needed to comment them ?

**Comment by ayewo** [comment]
Yes, it was already there but running the migration gave lots of errors that prevented supabase from starting up, which is why I commented them out rather than delete them as I explained when I opened this PR.

My goal was to get the DB up quickly so I could complete my investigation for https://github.com/Cap-go/capacitor-updater/issues/119.

As per your original request for this ticket: the app can be started successfully and I’ve made the instructions easier to follow, so I think it would be better to accept the temporary fix of commented out lines that I made in [`832740f`](https://github.com/Cap-go/capgo/pull/263/commits/832740fe64bfc21b80666e0113d098e3676ad5bf).

Some table names and relationships have changed and there are some pg extensions that are used that first need to be installed, so I humbly suggest creating a separate issue to:
 - fix the migration scripts that are broken and;
 - add seed data for the relevant tables in `seed.sql`.

**Comment by riderx** [comment]
Ok fair, I will tip you for this, and I will work on it to fix it.
Thanks

**Comment by ayewo** [comment]
@riderx That’s awesome! Thank you 👍.

**Comment by riderx** [comment]
@ayewo can you try the last commit i made i was able to generate schema file and start the supabase docker with new db.
Without migration files.
If that work i would like to merge your work for the doc only

**Comment by ayewo** [comment]
OK will do but I don't see your commits on my PR here or on the main repo https://github.com/Cap-go/capgo/tree/main

Perhaps you've not pushed it?

**Comment by riderx** [comment]
it's this file: https://github.com/Cap-go/capgo/blob/main/supabase/schema.sql

**Comment by ayewo** [comment]
I tried it on a fresh Linux box and it still fails:
```sh
pnpm backend

> capgo-app@10.35.0 backend /home/ubuntu/01_capgo
> supabase start && supabase functions serve

Seeding data supabase/seed.sql...
ERROR: relation "public.app_versions_meta" does not exist (SQLSTATE 42P01)
Try rerunning the command with --debug to troubleshoot the error.
 ELIFECYCLE  Command failed with exit code 1.
```


These are the versions that were downloaded when I tested your changes today:
```sh
public.ecr.aws/supabase/logflare              1.3.28           b1f3cb1bd8bf   8 days ago      433MB
public.ecr.aws/supabase/edge-runtime          v1.8.1           1cd2cd3edc0e   2 weeks ago     152MB
public.ecr.aws/supabase/postgres              15.1.0.103       b95a2ca21e7f   4 weeks ago     1.2GB
public.ecr.aws/supabase/gotrue                v2.82.4          9d3f77fe0840   4 weeks ago     40.7MB
public.ecr.aws/supabase/studio                v0.23.06         adf9c550b5c2   5 weeks ago     358MB
public.ecr.aws/supabase/storage-api           v0.40.4          6b6caa4ca77f   7 weeks ago     327MB
public.ecr.aws/supabase/postgres-meta         v0.66.3          c21236f55914   2 months ago    277MB
public.ecr.aws/supabase/realtime              v2.10.1          3737100a14c5   4 months ago    180MB
public.ecr.aws/supabase/postgrest             v11.1.0          3314f729eef6   4 months ago    17.1MB
public.ecr.aws/supabase/vector                0.28.1-alpine    f0494e814793   5 months ago    124MB
public.ecr.aws/supabase/imgproxy              v3.8.0           25d21ff36e2b   10 months ago   173MB
public.ecr.aws/supabase/kong                  2.8.1            3cefb958bcd6   10 months ago   139MB
public.ecr.aws/supabase/pgadmin-schema-diff   cli-0.0.5        68f44796bec4   12 months ago   244MB
public.ecr.aws/supabase/inbucket              3.0.3            f5b6afda5922   12 months ago   25.8MB
public.ecr.aws/supabase/migra                 3.0.1621480950   e2d4ea346dcc   2 years ago     66.5MB
```

Can you share the version of the docker images you have downloaded for supabase?

**Comment by riderx** [comment]
oh you are right i have the same weird issue.
I will try to fix it

**Comment by ayewo** [comment]
I tested the `main` branch and it worked!!

You did it 💪🎖️!

**Comment by riderx** [comment]
Can you update the PR to let me merge it :)

**Comment by ayewo** [comment]
Opening another PR was faster 😁.

Please see https://github.com/Cap-go/capgo/pull/268

**Pull request closed without merging**
