### PR TITLE
fix: Fix pricing display

### LINKED ISSUE #376: Fix pricing display
In the webapp the Pay as you go pricing are missing compare to landing page:
CleanShot 2023-09-19 at 08 24 53@2x
Webapp:
CleanShot 2023-09-19 at 08 25 14@2x

The price data is available in the DB data, use it from here
Pricing are display in Euro while billed in $, so dollar should be used.

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
fix #376
/claim #376

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
Screenshot 2023-09-19 at 2 38 35 PM
Screenshot 2023-09-19 at 2 38 46 PM

**Comment by riderx** [comment]
The important missing part is the price of addition user, storage and bandwidth

**Comment by rishi-raj-jain** [comment]
@riderx 

Fixed

**Comment by rishi-raj-jain** [comment]
also, added a commit to https://github.com/Cap-go/capgo/pull/378/files#diff-107e910e9f2ebfb9a741fa10b2aa7100cc1fc4f5f3aca2dfe78b905cbd73c0d2 so that it checks out the repo/branch from which the PR is created.

**Comment by rishi-raj-jain** [comment]
also, added a commit to https://github.com/Cap-go/capgo/pull/378/files#diff-107e910e9f2ebfb9a741fa10b2aa7100cc1fc4f5f3aca2dfe78b905cbd73c0d2 so that it checks out the repo/branch from which the PR is created.

**Comment by rishi-raj-jain** [comment]
Screenshot 2023-09-19 at 7 24 28 PM
Screenshot 2023-09-19 at 7 24 37 PM
Screenshot 2023-09-19 at 7 24 49 PM

**Comment by rishi-raj-jain** [comment]
so in the code I also check to see if each unit is available (from the backend), and only then those strings are updated to show this much additional cost per user

**Pull request merged**
