### PR TITLE
Fix deleting account

### PR DESCRIPTION
**Pull request by WcaleNieWolny**
Fixes https://github.com/Cap-go/capgo/issues/278

Changes:
 
 * It generates hash client side
 * Adds a rule allowing for inserting hashed email
 * Fixes cascade for notifications
 
 Feel free to reject if you do not like these changes or think that I should not get this bounty as I am the 3rd person to claim it

/claim #278

### CODE REVIEW

**Review by Szczurowsky — APPROVED** [review]
LGTM!

**Comment by riderx** [comment]
This will be close in favor of https://github.com/Cap-go/capgo/pull/279

**Comment by riderx** [comment]
The check login part will be used in your PR so for this i tip you

**Pull request closed without merging**
