### PR TITLE
✨ (feat): Allow the creation of an overwrite for a not listed device

### LINKED ISSUE #778: allow add override in front from not listed devices
**Describe the bug/issue**

### PR DESCRIPTION
**Pull request by WcaleNieWolny**
Fixes #778

### CODE REVIEW

**Comment by WcaleNieWolny** [comment]
@riderx ready for review

**Comment by WcaleNieWolny** [comment]
This PR lack proper permission checking for orgs

**Comment by riderx** [comment]
The feature should be present in 2 places:
- Main device list, and be as you created it.
- Device list of a channel, and don't ask for channel just device ID

**Comment by WcaleNieWolny** [comment]
> The feature should be present in 2 places:
> 
> * Main device list, and be as you created it.
> * Device list of a channel, and don't ask for channel just device ID

Resolved consecutively in https://github.com/Cap-go/capgo/pull/780/commits/4e75f6da6de5858436b2c47af83f48a9d6365906 and https://github.com/Cap-go/capgo/pull/780/commits/e7ab6e3eb73771097d077b54ce904e22b9e31225

**Comment by WcaleNieWolny** [comment]
Here is the video:

https://github.com/user-attachments/assets/a344e77b-6c3a-41ff-a136-71fe027722b2

**Pull request merged**
