### PR TITLE
✨ (feat): Partial upload (v2)

### PR DESCRIPTION
**Pull request by WcaleNieWolny**
Rebased #801 with fixed issues mentioned in #801

### CODE REVIEW

**Comment by riderx** [comment]
why do you rebase and recreate a PR each time?

**Comment by WcaleNieWolny** [comment]
I rebased and squashed because I felt like learning rebase.

From my understanding:
1. You rebase to avoid a 3-way merge commit.
2. Rebasing allows you to do a fast-forward merge
3. Squashing helps with the git commit history. It removes nonsensical commits that made sense in the scope of the PR but that do not make sense in the scope of the main branch
4. You NEVER rewrite history for a branch that was already shared with a co-worker, thus I created a new PR

**Comment by riderx** [comment]
By doing that, we lose the full history of the conversation.

The best way to do what you want for me is keep pushing commit on the same branch he resolves your issue and squash to remove the history of unwanted changes.
And this is ok to do it on your current branch without switching as no one else of you should have uncommit changes on this branch.
So people will just force pull if they did pull before.
Please do no create multiple branches and PR for the same task in the future. The history of the conversation is essential to me.

**Comment by WcaleNieWolny** [comment]
So, in practice, you are saying that I CAN squash commits but I just have to force push instead of creating a new branch?

**Pull request merged**
