### PR TITLE
fix: different behaviour between browsers

### LINKED ISSUE #320: Difftent behaviour between browsers
In brave (chromium based) I found a weird scroll bar in the UI
image

In firefox this scrollbar does not exist
image

I tested this in prod, here is the setup I used

image
image

### PR DESCRIPTION
**Pull request by chirag-jn**
/claim #320 
fixes #320

### CODE REVIEW

**Comment by WcaleNieWolny** [comment]
I will take a look at this in about 30 minutes

**Comment by chirag-jn** [comment]
Related information: https://www.w3schools.com/css/css_overflow.asp

**Comment by WcaleNieWolny** [comment]
It makes things better, and I would even say that it is good enough. However there still is some differences between chrome and firefox

https://github.com/Cap-go/capgo/assets/50914789/3abfdecf-8db5-458f-87c1-73cdadd3f1d1

Firefox has 2 scrollbars where brave (chromium) only has 1

**Comment by chirag-jn** [comment]
@WcaleNieWolny can you give it another try?

**Comment by WcaleNieWolny** [comment]
On it!

**Comment by WcaleNieWolny** [comment]
It does make the behavior the save in both browsers, so it does resolve the issue but I think that if we are not going to fix this double scroll bar issue then having it only in firefox is better then in both browsers

https://github.com/Cap-go/capgo/assets/50914789/982b47d1-f2fe-446a-b207-2d77bf462294

**Comment by chirag-jn** [comment]
As an alternative, we can either set `height: 100%` or set class as `overflow-y-hidden` on the parent div. What say?

**Comment by WcaleNieWolny** [comment]
> set class as `overflow-y-hidden`

Replace your `overflow-y-auto` with `overflow-y-hidden` and it does work in both browsers.


https://github.com/Cap-go/capgo/assets/50914789/82bfb5fd-5fc0-400a-8c4e-48a620cc9b8a

**Comment by chirag-jn** [comment]
Yep! That's what I am talking about. Made a patch for the same.

**Comment by rishi-raj-jain** [comment]
Way to go, @chirag-jn!

**Review by WcaleNieWolny — APPROVED** [review]

**Comment by riderx** [comment]
Hey @chirag-jn thanks for the work, the other PR was ready to merge when this one was having conflict so i used the other one.
I will still tip you for trying

**Comment by chirag-jn** [comment]
Probably the conflict happened because you merged PR #322 before this one.

**Comment by kremedev** [comment]
> Probably the conflict happened because you merged PR #322 before this one.

At least thank him for the tip.

**Comment by riderx** [comment]
You are right,
I went fast, I'm sorry I didn't compare them properly.
Next time I will be more careful

**Comment by riderx** [comment]
Thanks @kremedev all together we will improve

**Pull request closed without merging**
