### PR TITLE
Allowed change email

### PR DESCRIPTION
**Pull request by ayusham001**

### CODE REVIEW

**Comment by ayusham001** [comment]
@riderx 
Please review my PR
Let me know if I can make any other improvements.

**Comment by riderx** [comment]
Hello, thanks @ayusham001 for the work, this doesn't follow the requirement shared in the issue.
There are 2 places where the email should be updated.
You don't check if email is already in use.

**Comment by ayusham001** [comment]
@riderx 
Thanks for sharing
1st place is the user dashboard
And what is the another place wher

**Comment by riderx** [comment]
table users column email in public schema, please read the task description it's in it

**Comment by riderx** [comment]
Sorry someone clammed the bounty before you

**Pull request closed without merging**
