### PR TITLE
fix: stats landing

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
fix https://github.com/Cap-go/website/issues/62
/claim https://github.com/Cap-go/website/issues/62

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
`get_total_stats_v2` shall stay as is as that's the rpc I can see referring to current_usage

**Comment by riderx** [comment]
Can you fix your conflict ?

**Comment by rishi-raj-jain** [comment]
Sure!

**Comment by riderx** [comment]
CleanShot 2023-09-04 at 20 04 20@2x
CleanShot 2023-09-04 at 20 03 48@2x
In both pages i should see data as user.
in the chart and in the Bottom bar.
Screen 1:
The chart are empty where i should see data.
see the data in the db for MAU:
CleanShot 2023-09-04 at 20 08 07@2x
It seems storage and bandwidth need to be fixed in backend side but if you make work MAU all works.

Also channels, bundles, devices and updates should have a query now and not rely on old table app_stats.

Ignore the count of updates for now, for devices use the plan period to count them.
In second screen in the table my apps, the count of total MAU on plan period should be used.

**Comment by rishi-raj-jain** [comment]
@riderx Shall be good to go at https://github.com/Cap-go/capgo/pull/334

**Pull request closed without merging**
