### PR TITLE
feat: implement regenerating API key

### PR DESCRIPTION
**Pull request by WcaleNieWolny**
This PR implements the ability to regenerate API keys. I have included a demo of that below

https://github.com/Cap-go/capgo/assets/50914789/4a7d38ce-fbbc-46b3-bc53-fbbfbdc73dd0

Please note that that I18n translations would be nice, also if someone has any idea on how to improve `computedValue` please let me know

/claim #265

### CODE REVIEW

**Comment by riderx** [comment]
Thanks a lot for working on that.
Sadly, this is not acceptable as it is.
Capgo have backend function only when nothing else can be done.
With a good RLS this can be done in frontend fully.

Secondly, the Bounty is for delete add and renew.
And lastly, renew a key should be after alert.
I will add that to the initial issue.

**Comment by WcaleNieWolny** [comment]
Here is a video of how this changes look like currently:

https://github.com/Cap-go/capgo/assets/50914789/bf18baab-f47c-491a-a33d-a59340b389ad

**Review by riderx — APPROVED** [review]

**Comment by riderx** [comment]
perfect !

**Comment by WcaleNieWolny** [comment]
I will fix this today or if I am not able to today I will fix this in the morning (in about 14 hours)

**Comment by riderx** [comment]
Thanks !

**Pull request merged**
