### PR TITLE
feat: tests for org's CRUD

### PR DESCRIPTION
**Pull request by WcaleNieWolny**

### CODE REVIEW

**Comment by riderx** [comment]
Are we good with this ?

**Comment by WcaleNieWolny** [comment]
@riderx you can merge ^^

**Comment by WcaleNieWolny** [comment]
I forgot to include the migration, this caused the tests to fail

**Comment by riderx** [comment]
Still failing

**Comment by WcaleNieWolny** [comment]
> Still failing

no it's not: https://github.com/Cap-go/capgo/actions/runs/12210329962/job/34066273585

**Pull request merged**
