### PR TITLE
Add E2E tests and precommit hooks

### PR DESCRIPTION
**Pull request by neo773**
This PR lays the ground work for End-to-end tests
Currently only has one test for login

Also added husky precommit hooks

https://github.com/Cap-go/capgo/assets/62795688/d82beff2-42bf-4397-ab71-f36d6859ece4

/claim #342

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
@neo773 Can you change the file name to .env.ex**a**mple and not .env.ex**e**mple?

**Comment by rishi-raj-jain** [comment]
@riderx did you have a look at my review? I think there are some things that we needed to make sure before merging the PR.

**Comment by riderx** [comment]
I just saw your comment about file name, i saw a commit after it so i believed that was done

**Comment by rishi-raj-jain** [comment]
Nah there were other things to be addressed as well...

**Comment by rishi-raj-jain** [comment]
https://github.com/Cap-go/capgo/pull/345/files/531ac9e25fd5a27126ee23c398fdfbecd144c6f5#diff-236737c1dd4c90b4b7013221263ad002b0cdddb4716de2ab2829285d1272a538 is also important for accessibility.

**Comment by rishi-raj-jain** [comment]
Yeah, that makes sense, the final diff looks right for the button.

**Comment by rishi-raj-jain** [comment]
@riderx do you want to get the file name changed?

**Comment by rishi-raj-jain** [comment]
I can push that in #334

**Comment by rishi-raj-jain** [comment]
doen

**Pull request merged**
